async function updateShopping(id,patch){ const it=state.shopping.find(x=>x.id===id); await db.put(STORE.shopping,{...it,...patch,updatedAt:new Date().toISOString()}); await refreshState();renderAll(); }

function openPurchaseModal(item){
  renderModal(`<div class="modal-header"><div><p class="eyebrow">Barang terbeli</p><h2>${escapeHtml(item.name)}</h2></div><button class="close-button" data-close-modal>×</button></div><div class="modal-body form-grid"><div class="field-group"><label>Jumlah aktual</label><input id="purchaseAmount" type="number" min="0" step="0.01" value="${item.amount||''}"></div><div class="field-group"><label>Satuan</label><input id="purchaseUnit" value="${escapeHtml(item.unit||'')}"></div><div class="field-group"><label>Lokasi</label><select id="purchaseLocation"><option>kulkas</option><option>freezer</option><option selected>rak</option></select></div><div class="field-group"><label>Kedaluwarsa (opsional)</label><input id="purchaseExpiry" type="date"></div></div>`,{footer:`<button class="secondary-button" data-close-modal>Batal</button><button class="primary-button" id="confirmPurchaseBtn">Tambah ke stok</button>`});
  document.getElementById('confirmPurchaseBtn').onclick=async()=>{ const amount=Number(document.getElementById('purchaseAmount').value); const unit=normalizeUnit(document.getElementById('purchaseUnit').value); if(!(amount>0)||!unit){toast('Isi jumlah dan satuan aktual.');return;} await db.put(STORE.stock,{id:safeUUID(),name:item.name,amount,unit,location:document.getElementById('purchaseLocation').value,expiresAt:document.getElementById('purchaseExpiry').value||null,lowStockThreshold:null,note:'Ditambahkan dari daftar belanja',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}); await db.put(STORE.shopping,{...item,checked:true,updatedAt:new Date().toISOString()}); await refreshState();renderAll();closeModal();toast('Stok bertambah sesuai jumlah aktual.'); };
}

function openStockModal(existing=null){
  renderModal(`<div class="modal-header"><div><p class="eyebrow">${existing?'Koreksi stok':'Stok baru'}</p><h2>${existing?'Edit bahan':'Tambah bahan'}</h2></div><button class="close-button" data-close-modal>×</button></div><form id="stockForm" class="modal-body form-grid"><div class="field-group full"><label>Nama bahan</label><input name="name" required value="${escapeHtml(existing?.name||'')}"></div><div class="field-group"><label>Jumlah</label><input name="amount" type="number" min="0" step="0.01" required value="${existing?.amount??''}"></div><div class="field-group"><label>Satuan</label><input name="unit" required placeholder="gram, ml, buah…" value="${escapeHtml(existing?.unit||'')}"></div><div class="field-group"><label>Lokasi</label><select name="location"><option ${existing?.location==='kulkas'?'selected':''}>kulkas</option><option ${existing?.location==='freezer'?'selected':''}>freezer</option><option ${!existing||existing?.location==='rak'?'selected':''}>rak</option></select></div><div class="field-group"><label>Tanggal kedaluwarsa</label><input name="expiresAt" type="date" value="${existing?.expiresAt||''}"></div><div class="field-group"><label>Batas stok menipis</label><input name="lowStockThreshold" type="number" min="0" step="0.01" value="${existing?.lowStockThreshold??''}"></div><div class="field-group full"><label>Catatan</label><textarea name="note" rows="2">${escapeHtml(existing?.note||'')}</textarea></div></form>`,{footer:`<button class="secondary-button" data-close-modal>Batal</button><button class="primary-button" id="saveStockBtn">Simpan stok</button>`});
  document.getElementById('saveStockBtn').onclick=()=>document.getElementById('stockForm').requestSubmit();
  document.getElementById('stockForm').onsubmit=async e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const now=new Date().toISOString(); const value={id:existing?.id||safeUUID(),name:String(fd.get('name')).trim(),amount:Number(fd.get('amount')),unit:normalizeUnit(fd.get('unit')),location:fd.get('location'),expiresAt:fd.get('expiresAt')||null,lowStockThreshold:fd.get('lowStockThreshold')===''?null:Number(fd.get('lowStockThreshold')),note:String(fd.get('note')||'').trim(),createdAt:existing?.createdAt||now,updatedAt:now}; await db.put(STORE.stock,value);await refreshState();renderAll();closeModal();toast('Stok disimpan.');};
}

function parseStockInput(){
  const text=document.getElementById('quickStockInput').value.trim(); if(!text){toast('Ketik stok dulu.');return;} const parts=text.split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean); const unitPattern='kg|kilogram|ons|g|gr|gram|l|liter|ml|mililiter|cc|buah|butir|siung|batang|lembar|sachet|bungkus|ikat|sdm|sdt|cm|piring|ruas|ekor|gelas|genggam';
  const parsed=parts.map(p=>{ const m=p.match(new RegExp(`^(.+?)\\s+(\\d+(?:[.,]\\d+)?)\\s*(${unitPattern})$`,'i')); return m?{name:m[1].trim(),amount:Number(m[2].replace(',','.')),unit:normalizeUnit(m[3]),location:'rak'}:{name:p,amount:'',unit:'',location:'rak'}; });
  const root=document.getElementById('stockParseReview'); root.hidden=false; root.innerHTML=`<div class="parse-review"><h3>Periksa sebelum disimpan</h3><p class="helper">Parser lokal hanya memecah teks. Koreksi nama, jumlah, satuan, dan lokasi jika perlu.</p>${parsed.map((x,idx)=>`<div class="parse-grid" data-parse-row="${idx}"><div class="field-group"><label>Nama</label><input data-p-name value="${escapeHtml(x.name)}"></div><div class="field-group"><label>Jumlah</label><input data-p-amount type="number" step="0.01" value="${x.amount}"></div><div class="field-group"><label>Satuan</label><input data-p-unit value="${escapeHtml(x.unit)}"></div><div class="field-group"><label>Lokasi</label><select data-p-location><option>rak</option><option>kulkas</option><option>freezer</option></select></div><button class="small-icon" data-remove-parse="${idx}" aria-label="Hapus baris">×</button></div>`).join('')}<div class="inline-actions"><button class="primary-button" id="saveParsedStock">Simpan stok</button><button class="text-button" id="cancelParsedStock">Batal</button></div></div>`;
  root.querySelectorAll('[data-remove-parse]').forEach(b=>b.onclick=()=>b.closest('[data-parse-row]').remove()); document.getElementById('cancelParsedStock').onclick=()=>{root.hidden=true;root.innerHTML='';}; document.getElementById('saveParsedStock').onclick=saveParsedStock;
}
async function saveParsedStock(){
  const rows=[...document.querySelectorAll('[data-parse-row]')]; let saved=0; for(const row of rows){ const name=row.querySelector('[data-p-name]').value.trim(); const amount=Number(row.querySelector('[data-p-amount]').value); const unit=normalizeUnit(row.querySelector('[data-p-unit]').value); if(!name||!(amount>=0)||!unit) continue; const now=new Date().toISOString(); await db.put(STORE.stock,{id:safeUUID(),name,amount,unit,location:row.querySelector('[data-p-location]').value,expiresAt:null,lowStockThreshold:null,note:'',createdAt:now,updatedAt:now});saved++; }
  await refreshState();renderAll(); document.getElementById('stockParseReview').hidden=true; document.getElementById('stockParseReview').innerHTML=''; document.getElementById('quickStockInput').value=''; toast(`${saved} stok disimpan.`);
}