function openRecipeEditor(existing=null, draft=null){
  const r=safeClone(existing||draft||{id:safeUUID(),title:'',category:'Lainnya',mainIngredient:'',description:'',servings:2,servingsEstimate:false,prepMinutes:null,cookMinutes:null,timeEstimate:false,favorite:false,image:{type:'placeholder',exactMatch:false,alt:'',sourcePageUrl:'',creator:'',...pixabayLicense},source:{type:'manual',label:'Input manual'},ingredients:[],steps:[],notes:''});
  renderModal(`<div class="modal-header"><div><p class="eyebrow">${existing?'Edit':'Resep baru'}</p><h2>${existing?'Edit resep':'Tambah resep'}</h2></div><button class="close-button" data-close-modal>×</button></div><form id="recipeForm" class="modal-body form-grid"><div class="field-group full"><label>Nama resep</label><input name="title" required value="${escapeHtml(r.title)}"></div><div class="field-group"><label>Kategori</label><input name="category" value="${escapeHtml(r.category||'')}"></div><div class="field-group"><label>Bahan utama</label><input name="mainIngredient" value="${escapeHtml(r.mainIngredient||'')}"></div><div class="field-group full"><label>Deskripsi</label><textarea name="description" rows="2">${escapeHtml(r.description||'')}</textarea></div><div class="field-group"><label>Porsi</label><input name="servings" type="number" min="0.5" step="0.5" value="${r.servings||''}"></div><div class="field-group"><label><input name="servingsEstimate" type="checkbox" ${r.servingsEstimate?'checked':''} style="width:auto"> Porsi ini perkiraan</label></div><div class="field-group"><label>Persiapan (menit)</label><input name="prepMinutes" type="number" min="0" value="${r.prepMinutes??''}"></div><div class="field-group"><label>Masak (menit)</label><input name="cookMinutes" type="number" min="0" value="${r.cookMinutes??''}"></div><div class="field-group full"><label><input name="timeEstimate" type="checkbox" ${r.timeEstimate?'checked':''} style="width:auto"> Waktu ini perkiraan</label></div><div class="field-group full"><label>URL foto langsung (opsional)</label><input name="imageUrl" type="url" value="${escapeHtml(r.image?.url||'')}" placeholder="https://…"><small class="helper">Kosongkan jika belum ada aset internet dengan lisensi yang sudah diverifikasi.</small></div><div class="field-group full"><label>Halaman sumber foto</label><input name="imageSource" type="url" value="${escapeHtml(r.image?.sourcePageUrl||'')}"></div><div class="field-group full"><label>Alt text foto</label><input name="imageAlt" value="${escapeHtml(r.image?.alt||'')}"></div><div class="field-group full"><label>Bahan</label><div id="ingredientEditor" class="dynamic-list">${r.ingredients.map(ingredientEditorRow).join('')}</div><button type="button" class="text-button" id="addIngredientRow">+ Tambah bahan</button></div><div class="field-group full"><label>Langkah</label><div id="stepEditor" class="dynamic-list">${r.steps.map(stepEditorRow).join('')}</div><button type="button" class="text-button" id="addStepRow">+ Tambah langkah</button></div><div class="field-group full"><label>Catatan pribadi</label><textarea name="notes" rows="3">${escapeHtml(r.notes||'')}</textarea></div></form>`,{wide:true,footer:`${existing?'<button class="danger-button" id="deleteRecipeBtn">Hapus resep</button>':''}<button class="secondary-button" data-close-modal>Batal</button><button class="primary-button" id="saveRecipeBtn">Simpan resep</button>`});
  document.getElementById('addIngredientRow').onclick=()=>document.getElementById('ingredientEditor').insertAdjacentHTML('beforeend',ingredientEditorRow(i('',null,'')));
  document.getElementById('addStepRow').onclick=()=>document.getElementById('stepEditor').insertAdjacentHTML('beforeend',stepEditorRow(''));
  document.getElementById('recipeForm').addEventListener('click',e=>{ if(e.target.matches('[data-remove-dynamic]')) e.target.closest('.dynamic-row').remove(); });
  document.getElementById('saveRecipeBtn').onclick=()=>document.getElementById('recipeForm').requestSubmit();
  document.getElementById('recipeForm').onsubmit=async e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); r.title=String(fd.get('title')).trim();r.category=String(fd.get('category')).trim()||'Lainnya';r.mainIngredient=String(fd.get('mainIngredient')).trim();r.description=String(fd.get('description')).trim();r.servings=Number(fd.get('servings'))||1;r.servingsEstimate=fd.get('servingsEstimate')==='on';r.prepMinutes=fd.get('prepMinutes')===''?null:Number(fd.get('prepMinutes'));r.cookMinutes=fd.get('cookMinutes')===''?null:Number(fd.get('cookMinutes'));r.timeEstimate=fd.get('timeEstimate')==='on';r.notes=String(fd.get('notes')).trim();r.image={...r.image,type:fd.get('imageUrl')?'internet':'placeholder',url:String(fd.get('imageUrl')||'').trim()||undefined,sourcePageUrl:String(fd.get('imageSource')||'').trim(),alt:String(fd.get('imageAlt')||'').trim()||r.title};r.ingredients=[...document.querySelectorAll('#ingredientEditor .dynamic-row')].map(row=>({id:safeUUID(),name:row.querySelector('[data-ing-name]').value.trim(),amount:row.querySelector('[data-ing-amount]').value===''?null:Number(row.querySelector('[data-ing-amount]').value),unit:normalizeUnit(row.querySelector('[data-ing-unit]').value),optional:row.querySelector('[data-ing-optional]').checked,note:''})).filter(x=>x.name);r.steps=[...document.querySelectorAll('#stepEditor [data-step-text]')].map(x=>x.value.trim()).filter(Boolean);r.updatedAt=new Date().toISOString();r.createdAt=r.createdAt||r.updatedAt;await db.put(STORE.recipes,r);await refreshState();renderAll();closeModal();toast('Resep disimpan.');};
  if(existing) document.getElementById('deleteRecipeBtn').onclick=async()=>{if(confirm(`Hapus resep “${r.title}”?`)){await db.delete(STORE.recipes,r.id);await refreshState();renderAll();closeModal();toast('Resep dihapus.');}};
}
function ingredientEditorRow(ing){ return `<div class="dynamic-row"><input data-ing-name placeholder="Nama bahan" value="${escapeHtml(ing.name||'')}"><input data-ing-amount type="number" step="0.01" placeholder="Jumlah" value="${ing.amount??''}"><input data-ing-unit placeholder="Satuan" value="${escapeHtml(ing.unit||'')}"><label class="check-label"><input data-ing-optional type="checkbox" ${ing.optional?'checked':''}> Opsional</label><button type="button" class="small-icon" data-remove-dynamic>×</button></div>`; }
function stepEditorRow(step){ return `<div class="dynamic-row step"><textarea data-step-text rows="2" placeholder="Langkah memasak…">${escapeHtml(step||'')}</textarea><button type="button" class="small-icon" data-remove-dynamic>×</button></div>`; }

function openImportRecipe(){
  renderModal(`<div class="modal-header"><div><p class="eyebrow">Impor resep</p><h2>Tempel teks atau percakapan</h2></div><button class="close-button" data-close-modal>×</button></div><div class="modal-body"><div class="warning-box"><strong>AI belum terhubung.</strong> Versi ini memakai ekstraksi lokal sederhana dan tidak mengarang takaran atau waktu yang tidak ada.</div><label for="importText"><strong>Teks resep</strong></label><textarea id="importText" rows="14" placeholder="Tempel resep di sini…"></textarea></div>`,{footer:`<button class="secondary-button" data-close-modal>Batal</button><button class="primary-button" id="extractRecipeBtn">Tinjau hasil ekstraksi</button>`});
  document.getElementById('extractRecipeBtn').onclick=()=>{const text=document.getElementById('importText').value.trim();if(!text){toast('Tempel teks resep dulu.');return;}const draft=parseRecipeText(text);openRecipeEditor(null,draft);};
}
function parseRecipeText(text){
  const lines=text.split('\n').map(x=>x.trim()).filter(Boolean); const title=(lines[0]||'Resep impor').replace(/^#+\s*/,'').slice(0,100); let mode=''; const ingredients=[],steps=[]; const amountRx=/^(?:[-*•]\s*)?(.+?)\s+(\d+(?:[.,]\d+)?)\s*(kg|g|gram|ml|l|liter|buah|butir|siung|batang|lembar|sachet|bungkus|ikat|sdm|sdt|cm)\b/i;
  for(const line of lines.slice(1)){ if(/bahan/i.test(line)&&line.length<40){mode='ingredients';continue;} if(/cara|langkah/i.test(line)&&line.length<60){mode='steps';continue;} if(mode==='ingredients'){const m=line.match(amountRx); if(m) ingredients.push({id:safeUUID(),name:m[1].replace(/^[-*•]\s*/,''),amount:Number(m[2].replace(',','.')),unit:normalizeUnit(m[3]),optional:/opsional/i.test(line),note:''}); else ingredients.push({id:safeUUID(),name:line.replace(/^[-*•]\s*/,''),amount:null,unit:'',optional:false,note:'Takaran belum terdeteksi'});} else if(mode==='steps') steps.push(line.replace(/^\d+[.)]\s*/,'')); }
  return {id:safeUUID(),title,category:'Lainnya',mainIngredient:'',description:'Hasil impor teks — periksa sebelum menyimpan.',servings:2,servingsEstimate:true,prepMinutes:null,cookMinutes:null,timeEstimate:false,favorite:false,image:{type:'placeholder',exactMatch:false,alt:title,sourcePageUrl:'',creator:'',...pixabayLicense},source:{type:'import',label:'Teks impor'},ingredients,steps,notes:'Periksa kembali hasil ekstraksi lokal sebelum disimpan.'};
}

function openShoppingModal(){
  renderModal(`<div class="modal-header"><div><p class="eyebrow">Belanja manual</p><h2>Tambah item</h2></div><button class="close-button" data-close-modal>×</button></div><div class="modal-body form-grid"><div class="field-group full"><label>Nama bahan</label><input id="shopName"></div><div class="field-group"><label>Jumlah</label><input id="shopAmount" type="number" step="0.01" min="0"></div><div class="field-group"><label>Satuan</label><input id="shopUnit"></div></div>`,{footer:`<button class="secondary-button" data-close-modal>Batal</button><button class="primary-button" id="saveShoppingBtn">Tambahkan</button>`});
  document.getElementById('saveShoppingBtn').onclick=async()=>{const name=document.getElementById('shopName').value.trim();if(!name){toast('Nama bahan belum diisi.');return;}const amount=document.getElementById('shopAmount').value===''?null:Number(document.getElementById('shopAmount').value);const unit=normalizeUnit(document.getElementById('shopUnit').value);await mergeShopping({name,amount,unit,recipeTitle:''});await refreshState();renderAll();closeModal();toast('Ditambahkan ke daftar belanja.');};
}

async function exportData(){ const data={version:1,exportedAt:new Date().toISOString(),recipes:state.recipes,stock:state.stock,shopping:state.shopping,transactions:state.transactions}; const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dapur-marlon-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500); }
function toast(message){ const el=document.createElement('div');el.className='toast';el.textContent=message;document.getElementById('toastRegion').append(el);setTimeout(()=>el.remove(),3200); }
function cap(s=''){ return s.charAt(0).toUpperCase()+s.slice(1); }
function formatDate(date){ return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(date+'T12:00:00')); }
function formatDateTime(date){ return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(date)); }


(function bootDapur(){ try{ if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded', function(){ try{ init(); }catch(e){ console.warn(e); } }, { once:true }); } else { init(); } }catch(e){ try{ init(); }catch(_){} } })();